### ISSUE TITLE
Setting more than two pronouns causes error during user data update

### ISSUE THREAD

**Issue by AshleyOmegaNova** [esamarathon/oengusio#113]
### Describe the bug

'Any' is not one of the pronoun options I seem able to pull from pronouns.page, so I tried to set he/him, they/them, _and_ she/her as my pronouns instead. On attempting to save this change to my profile, I got "Error during user data update." After testing with a few other pronouns, it seems any combination of more than two pronoun sets causes this.

### How to reproduce

1. Go to 'https://oengus.io/user/settings'
2. Click on the 'Pronouns' field
3. Add any three pronoun sets
4. Hit 'Save'
5. Error message displays 'Error during user data update'
6. The profile is not updated

### Expected behavior

The profile should update upon hitting Save

### Desktop (please complete the following information)

- OS: Windows
- Browser: Firefox

**Comment by duncte123** [comment]
The bug is that the pronouns field internally only allows up to 20 characters, this will be fixed in v2
