### ISSUE TITLE
Schedule fails to load due to SSL error.

### ISSUE THREAD

**Issue by Corvimae** [esamarathon/oengusio#118]
### Describe the bug

Attempting to load the Speedrun Ragnarok schedule redirects to v2 and causes a TLS issue:

```
An error occurred during a connection to v2.oengus.io. Peer reports it experienced an internal error.

Error code: SSL_ERROR_INTERNAL_ERROR_ALERT

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

### How to reproduce

Navigate to https://v2.oengus.io/en-GB/marathon/SRR2021/schedule

### Expected behavior

The page should load.

### Desktop (please complete the following information)

- OS: Mac OS 11.6 Big Sur
- Browser: Firefox
- Version: 92.0

**Comment by NetaraIllyandis** [comment]
More info: This issue is affecting all people who attempt to access this link, and apparently also every schedule currently on Oengus.

**Comment by BobChao87** [comment]
As a temporary workaround, you can remove the `v2.` and the language portion (e.g. `en-GB/`) to get a URL like https://oengus.io/marathon/LSS21/schedule

**Comment by BobChao87** [comment]
SSL/TLS error has been resolved, the schedule link should no longer throw you into the horrible void.

**Comment by duncte123** [comment]
Closing since the issue seems resolved
