### ISSUE TITLE
Horaro export: column names become "???" with Japanese locale

### ISSUE THREAD

**Issue by Hoishin** [esamarathon/oengusio#132]
### Describe the bug

when you export Horaro JSON, column names become "???" with Japanese locale

![image](https://user-images.githubusercontent.com/28832095/141651656-5a88da4c-7d94-4c50-a37a-d86d859ac373.png)

### How to reproduce

1. set locale to Japanese
2. export to Horaro
3. columns are mostly "???"

### Expected behavior

it should have correct Japanese column names

### Desktop (please complete the following information)

- OS: Windows
- Browser: Chrome
- Version: Windows 10, Chrome 95

**Comment by duncte123** [comment]
This seems to be bugged on weblate as well, the strings will need to be re-translated

**Comment by duncte123** [comment]
Is this still the case?

**Comment by duncte123** [comment]
Closing this issue as the strings have been translated
