### ISSUE TITLE
Schedule showing wrong run as current/next on v2

### ISSUE THREAD

**Issue by Arcorann** [esamarathon/oengusio#135]
### Describe the bug

Looking at the schedule of RTA in Japan Winter 2021. As of this writing (2021-12-27 16:53, UTC+11) the v2 schedule displays the Rabi-Ribi run (02:58) as current and Dragon Quest V (04:51) as next.

https://v2.oengus.io/en-GB/marathon/rtaijw2021/schedule

By contrast, the schedule on v1 shows the correct runs, Armored Core 3 (16:09) as current and Portal (17:37) as next.

https://oengus.io/marathon/rtaijw2021/schedule

### How to reproduce

Open the schedule for RTA in Japan Winter 2021 on the v2 site: https://v2.oengus.io/en-GB/marathon/rtaijw2021/schedule

### Expected behavior

v2 site should show current run matching the current time like v1 does

### Desktop (please complete the following information)

- OS: Windows 10
- Browser: Confirmed on Vivaldi 4.3.2439.65 and Firefox 94.0.2

### Additional context/screenshots

My timezone is currently Australian Eastern Daylight Savings Time (AEDST = UTC+11).

**Comment by duncte123** [comment]
I already know why, I have to adjust a cache rule so it doesn't cache the ticker

**Comment by duncte123** [comment]
That should be fixed now, let me know if it is

**Comment by Arcorann** [comment]
Confirmed, thanks for the quick response.
