### ISSUE TITLE
editsub doesn't display what was updated

### ISSUE THREAD

**Issue by riek-lt** [esamarathon/oengusio#145]
### Describe the bug

Way before, whenever a submission was changed, it actually showed the before and after. 
Example for Category: `Any% (was any% lols)`

And in the case a game or category description was altered, it showed that too. Now, there is no changelog

### How to reproduce

1. Enable editsub webhook
2. Create a submission
3. Edit anything in the submission
4. Check the discord channel to see "Updated a run in `marathon`"
5. Think of "hmm, what was changed?"
6. Cry in a corner

### Expected behavior

Show changes (see Platform)

![](https://cdn.discordapp.com/attachments/601096843199381504/959051736373415946/IMG_20220331_132845.jpg)

### Actual behavior

Doesn't show `was Y`

![](https://cdn.discordapp.com/attachments/942026702341685309/959213315228327936/unknown.png)

**Comment by duncte123** [comment]
Is this still the case?

**Comment by duncte123** [comment]
This has since been fixed
