### ISSUE TITLE
color combination of inline code markdown for protanopia

### ISSUE THREAD

**Issue by pingval** [esamarathon/oengusio#147]
### What is the feature?

I have mild protanopia. For me, the color combination of `` `inline code` `` markdown on https://v1.oengus.io/.../ (`#073642` and `#9b225c`) is difficult to distinguish.

### Describe the feature

I would like to see text color of `` `inline code` `` markdown changed so that even protanopia ealisy distinguish it.
I would modestly suggest like `#999955` or `#996655`.

### Additional context

vanilla
![vanilla](https://user-images.githubusercontent.com/40169989/167263883-e43ca062-a5c7-4cf8-a09f-c116c55f0fdf.png)

protanopia vision with Chrome DevTools
![protanopia](https://user-images.githubusercontent.com/40169989/167263890-2219ed6e-39eb-4f96-9838-37f60dff2a5e.png)

However, the number of event which uses `` `inline code` `` markdown that currently can be traced from https://v1.oengus.io/ is only one: https://v1.oengus.io/marathon/rtaijs2022

**Comment by duncte123** [comment]
Thank you for reporting this, I will try to get this out asap

**Comment by duncte123** [comment]
Changed the colour to `#ffc8e2`
