### ISSUE TITLE
Youtube link validation does not wotk with new Youtube tags

### ISSUE THREAD

**Issue by Gyoo** [esamarathon/oengusio#155]
### Describe the bug

Youtube has new channel tags for a few months, but the links are marked as invalid in the Marathon settings.

### How to reproduce

1. Go to marathon settings
2. Try to add a youtube link with the new link format, for instance https://www.youtube.com/@SpeeDons (the one I tried)
3. Validation rules mark the field as invalid.

### Expected behavior

The Youtube links including a channel @ tag should be valid

### Desktop (please complete the following information)

- OS: Windows
- Browser : firefox
- Version : 108.0

### Additional context/screenshots

![image](https://user-images.githubusercontent.com/3592205/208637572-77c74905-e707-42df-aade-ea4e6b6f07a3.png)

**Comment by duncte123** [comment]
Found the regex https://github.com/esamarathon/oengus-webapp/blob/v1/src/app/marathon/settings/settings.component.html#L363

**Comment by Gyoo** [comment]
Might be worth checking if there is something in the backend as well

**Comment by duncte123** [comment]
> Might be worth checking if there is something in the backend as well

There is no regex for this on the backend
