### ISSUE TITLE
Português (Brazil) and special characters as a marathon name not working

### ISSUE THREAD

**Issue by CesarMartins12** [esamarathon/oengusio#158]
### Describe the bug

I tried to create a arathon called BRAT Páscoa 2023 with the language Português (Brazil) and the website is not saving my marathon. 

When I change the name to BRAT Pascoa 2023 and change the language to any other, the website saves.

### How to reproduce

1. Go to '.....................'
2. Click on '..................'
3. Scroll down to '............'
4. Error message displays '....'
...
2. Submit (for a new marathon)

### Expected behavior

Save my marathon

### Desktop (please complete the following information)

- OS: [e.g. iOS, Ubuntu, Windows]
- Browser [e.g. chrome, safari, firefox]
- Version [e.g. 22, 20.04, 2004 19041.804]

**Comment by duncte123** [comment]
Dev notes:
`ERROR: value too long for type character varying(3)` for `pt_BR`, bumping it to 4 should be safe
The culprit of marathon name https://github.com/esamarathon/oengusio/blob/master/src/main/java/app/oengus/entity/model/Marathon.java#L34

**Comment by CesarMartins12** [comment]
I'm sorry but it was closed but the problem persists. 
I try to fix the marathon name and wtill doesn't accept the letter "á" just "a"

And the Portuguese(Brazil) language still not working and when I click submit give me an error

![language1](https://user-images.githubusercontent.com/92743088/213536519-1f105d02-a467-4b35-bfcb-89f2800b865f.PNG)
![NAME](https://user-images.githubusercontent.com/92743088/213536522-d698d7df-a5b0-4a57-b497-e4b018f8361a.PNG)
![name1](https://user-images.githubusercontent.com/92743088/213536524-f66a20cb-2ca0-4d52-9147-40cfd9b8269f.PNG)
![language](https://user-images.githubusercontent.com/92743088/213536526-3917d7a6-abcf-420f-9a4e-34ae03996fb6.PNG)
