### ISSUE TITLE
Add Mastodon in social networks and login platforms

### ISSUE THREAD

**Issue by Gyoo** [esamarathon/oengusio#159]
### What is the feature?

Mastodon is gaining a lot of traction lately, it may be relevant to add it to the list of social networks you can set on your profile, and maybe as another login platform, both as an alternative to Twitter.

### Describe the feature

- Profile settings should have a "Mastodon" field in the Connexions list
- Marathon settings should have a similar field
- Profile and Marathon pages should display the link to the Mastodon account if present
- (Optional) Add the possibility for a user to choose between Twitter and Mastodon as the social network they want to display next to their nickname
- (Optional) Add Mastodon as an OAuth2 platform

**Comment by duncte123** [comment]
Mastodon is already planned to replace login with twitter. (google oauth will also be added)
Currently working on fixing up the login flow to make sure that an account is not created before a user finishes signup.

**Comment by duncte123** [comment]
I am putting this on hold in favour of google login. 

With mastodon, we have to generate a client per instance, which is not fun to maintain.
