### ISSUE TITLE
Wrong times showing for an upcoming marathon

### ISSUE THREAD

**Issue by MrDino023** [esamarathon/oengusio#161]
### Describe the bug

Hi there, there was a weird bug in the times showing for our upcoming marathon next weekend.

To give some context, Mexico didn't change to Daylight savings (Today would've been the day that we would have done it)

However, since last November, it was rules that Mexico won't be changing clocks to DST, so no moving the clocks forward.

Many digital clocks did make the switch however and it was a confusion mess this morning due to that.

Anyways, with that piece of context as to what I think would've cause this issue with Oengus, if I go to the Manage schedule section, it shows the time properly, which is, Marathon will be starting at 15:00 local time.

However, if you go to the Schedule itself, it shows that it would start at 14:00 local time (So therefore, affecting all the runs forward)

I'm thinking maybe a quick workaround is that I just add a 1 hour setup block at the start.

This is the marathon in question:
https://oengus.io/en-GB/marathon/MaMeS2023/schedule
![image2](https://user-images.githubusercontent.com/101012206/229378805-e979d88f-7aea-49ec-8294-164d96de0d71.png)
![image](https://user-images.githubusercontent.com/101012206/229378806-292c4119-af41-444a-ab86-2912af9f6397.png)

### How to reproduce

Different times showing when managing schedule compared to public schedule preview

### Expected behavior

Same schedule to be shown (In actual local time)

### Desktop (please complete the following information)

This is happening for all users in multiple devices, OS and browsers.

### Smartphone (please complete the following information)

This is happening for all users in multiple devices, OS and browsers.

**Comment by duncte123** [comment]
I am assuming that v1 still did the DST change, is that correct?

**Comment by MrDino023** [comment]
It seems that was the case, so right now my local time is technically the same as Mountain time US, the rest of the year is the same as Central US.

So it seems to be thinking that the times inside the edit schedule are currently in CDT so it "converts" them to Mountain when I see them in preview

**Comment by duncte123** [comment]
> It seems that was the case, so right now my local time is technically the same as Mountain time US, the rest of the year is the same as Central US.
> 
> So it seems to be thinking that the times inside the edit schedule are currently in CDT so it "converts" them to Mountain when I see them in preview

When you look at the bottom of the page, is that also the timezone it is displaying? 
We use a library to detect the timezone, so an update might have fixed it already

**Comment by MrDino023** [comment]
It is showing "Mexico City" both in the preview as well as in the place to modify the schedule, however, the preview is still showing everything one hour earlier (Start time 14:00 on Friday) compared to the modify schedule time (15:00 on Friday which is the correct one)
![Preview Timezone](https://user-images.githubusercontent.com/101012206/229546534-4fcf8f5d-7fe2-4a4d-afb9-f312119cb118.JPG)
![Modify Schedule Timezone](https://user-images.githubusercontent.com/101012206/229546536-56bc306d-ddd5-4c16-b958-8ff45f6384ca.JPG)

**Comment by duncte123** [comment]
I'll see what I can do to fix this

**Comment by MrDino023** [comment]
Thank you so much for looking into this!

I'm not even sure if there would be an "easy" fix without doing something super weird, I see the same issue is happening in other tools (i.e. the discord event scheduling system) which I assume pulls the time conversions in a similar way.

Maybe I just add like an extra dummy block that lasts for 1 hour at the start of the whole schedule or something like that.

**Comment by duncte123** [comment]
That would be a good temporary fix yes

**Comment by duncte123** [comment]
Is this still an issue?
