### ISSUE TITLE
Users have invalid usernames after name migration

### ISSUE THREAD

**Issue by DorianSnowball** [esamarathon/oengusio#166]
### Describe the bug

Following the recent change to add Displaynames instead of usernames in [Version 2023.07.08](https://github.com/esamarathon/oengusio/releases/tag/v2023.07.08), some users have what appears to be a failed migration.

The announcement of Displaynames in the [Discord](https://discord.com/channels/601082577729880092/601096560012558337/1126822246560833636) states that all usernames are now lowercase.

However I found one user who still has a Username with a capitalized name.
This breaks multiple things in the Oengus Frontend with the submission showing no User and also the Frontend not returning the user page.
Directly calling the v1 API with the capitalized name does provide the expected result.

### How to reproduce

The identified user with the broken name format is (extract from a marathon submissions API call):
```json
"user": {
                "id": 13659,
                "username": "Kayumon",
                "displayName": null,
                "enabled": true,
                "pronouns": [],
                "country": null,
                "languagesSpoken": [],
                "connections": [
                    {
                        "id": 23805,
                        "platform": "DISCORD",
                        "username": "Kayumon#6794"
                    }
                ],
                "usernameJapanese": null
 }
``` 

Calling [https://oengus.io/api/v1/users/Kayumon](https://oengus.io/api/v1/users/Kayumon) does resolve successfully while calling [https://oengus.io/api/v1/users/kayumon](https://oengus.io/api/v1/users/kayumon) 404's.

The Frontend Page [https://oengus.io/user/Kayumon](https://oengus.io/user/Kayumon) does call the API with the lowercase name though and thous errors.

Submissions from that user seem to kind of work: Submission is there but there is no displayed name in either the submission overview or the Run Selection Page.

### Expected behavior

Every User should have a Displayname and a username following the rules for usernames.

### Additional context/screenshots

![run_selection_null_displayname](https://github.com/esamarathon/oengusio/assets/31218621/6af3699c-3ff3-4de1-a1c6-950c1042bb54)
![submission_overview_null_displayname](https://github.com/esamarathon/oengusio/assets/31218621/a0cbadde-ea80-467a-aa6e-c9d9146a9cf2)

**Comment by duncte123** [comment]
SQL failed me 🙃

**Comment by duncte123** [comment]
Fixed

**Comment by DorianSnowball** [comment]
Spotted another user without a Displayname: 

```json
    "id": 13761,
    "username": "andilulu",
    "displayName": null,
    [...]
```
This time around visiting the profile still works though and displays the Name as "(andilulu)".

So the fundamental issue does not seem to be fixed entirely.

**Comment by duncte123** [comment]
Updated 61 users
