### ISSUE TITLE
Schedule Manager tells which runner is not available

### ISSUE THREAD

**Issue by Floha258** [esamarathon/oengusio#172]
### What is the feature?

Currently when playing a run on a schedule where a runner is not available it tells you that a runner is not available by marking the entire runner red. It doesn't tell you however which runner is not available for a submissions with multiple people.

### Describe the feature

Instead of marking the entire run red, it could possibly mark the runner(s) red who don't fit into this slot anymore.

**Comment by duncte123** [comment]
How's this?

![example of the requested feature](https://entered.space/YAEaJxhSUE.png)

**Comment by Floha258** [comment]
Looks good, does just what it should do

**Comment by duncte123** [comment]
Added in https://github.com/esamarathon/oengus-webapp/commit/e15b07ca77c0892014c302112482b99f1434ae7a
