### ISSUE TITLE
Cannot access user profile of some users

### ISSUE THREAD

**Issue by Gyoo** [esamarathon/oengusio#173]
### Describe the bug

When I click on the name of some users, I cannot access their profile page and get a 404 error instead

### How to reproduce

1. Go to https://oengus.io/marathon/speedons4/submissions
2. Find the submission from user "Nexos_et_Shadows"
3. Click on their profile
4. 404 error
...

### Expected behavior

I should be able to reach their profile page properly

### Desktop (please complete the following information)

- OS: Windows 11 : 
- Browser : Firefox
- Version : 119.0.1

**Comment by duncte123** [comment]
Fixed, for some reason this user did not have a lowercase username
