### ISSUE TITLE
Unable to join multiplayer submission

### ISSUE THREAD

**Issue by CDRomatron** [esamarathon/oengusio#186]
### Describe the bug

After entering the code for the multiplayer submission and clicking join, nothing happens. There is no toast or visual indication anything has happened (or that anything failed).

Code in question: [redacted] for https://oengus.io/marathon/uksgblue24/

### How to reproduce

On: A marathons submissions page
Then scroll down and paste code in the box
Then press join

### Expected behavior

Joining the multiplayer submission (or error explaining that it could not add the player)

### Desktop (please complete the following information)

Device: PC
Browser: Google Chrome

### Smartphone (please complete the following information)

Device: Android
Browser: Google Chrome

**Comment by duncte123** [comment]
I've edtied your post to remove the multiplayer code, but please keep in mind that other people can join the submission when you share it

**Comment by duncte123** [comment]
I've tried a lot and published a few new versions and I cannot figure out why this is happening or reproduce it outside of production.

My current knowledge on this issue:
- category gets from database (works fine, added an index for fast but did not matter)
- Slowdown and no response. I have no clue where this is happening.
  - My current suspicion is that the call to  `SubmissionPersistencePort#getByGameId` is causing this slowdown, as I have optimised any subsequent database calls as much as possible. I'll have a look to see if I can optimize this, but I highly doubt it

**Comment by duncte123** [comment]
Update: The application code is not the problem, using a share code (somehow) works fine on sandbox

**Comment by duncte123** [comment]
I have added extra logging to the backend and saw that at least 1 person came through the entire flow. I think the backend is just overloaded currently and not able to process the sheer amount of requests it is getting. Looking into solutions

**Comment by duncte123** [comment]
@CDRomatron Would you mind re-trying? This should be fixed now

**Comment by CDRomatron** [comment]
Managed to join the COOP submission now. Thank you!
