### ISSUE TITLE
Console inputbox having 10 characters max

### ISSUE THREAD

**Issue by riek-lt** [esamarathon/oengusio#19]
**Is your feature request related to a problem? Please describe.**
Console inputbox can only have 10 characters in them, which makes the full Playstation name unusable, and similar to the ZX Spectru(m). For the PS, it's not bad since people can simply fill in PS2, but for some consoles it's not enough,

**Describe the solution you'd like**
EITHER:

- Maybe a 16 character limit
- Have a dropdown list of all consoles currently submitters can choose from. This does give uniformity, and would help my statistics page to be a bit more uniform.

**Comment by duncte123** [comment]
If you can provide me with a list of all the consoles I'll happily add the dropdown

**Comment by riek-lt** [comment]
I got the following list for now, with a lot of realistic consoles added. I didn't add stuff like "Wii VC" or "MSX" as those are quite unlikely (but not impossible) to appear at one point.
https://pastebin.com/1bSqiGKy
