### ISSUE TITLE
Setup blocks don't work with horaro import

### ISSUE THREAD

**Issue by riek-lt** [esamarathon/oengusio#27]
**Describe the bug**
Whenever I download the CSV for my marathon, and upload it to horaro, horaro errors out because the estimate is 0 minutes, with the setup buffer being as long as it's set here. Can the "input" be that duration, and setup block 0 minutes?

**To Reproduce**
1. have schedule with empty field/setup buffer
2. export csv
3. upload to horaro

**Expected behavior**
Horaro to pass OpieOP

**Comment by duncte123** [comment]
Try this option instead 
![image](https://user-images.githubusercontent.com/8843386/109528037-95bfa980-7ab4-11eb-85e5-07beeabfe442.png)

**Comment by duncte123** [comment]
issue tracking: Imports fail due to an estimate of `00:00:00`, horaro accepts null for these
