### ISSUE TITLE
Translation license AGPLv3 "only" instead of "or-later"

### ISSUE THREAD

**Issue by comradekingu** [esamarathon/oengusio#34]
Looking at https://hosted.weblate.org/accounts/profile/#licenses all the Oengus components are for some reason licensed "only", instead of "or-later". Is this an error?
https://hosted.weblate.org/projects/oengusio/#information

I am https://hosted.weblate.org/user/kingu/ on there, and I can't request nb_NO (Norwegian Bokmål) since I don't use Discord.
(Edit: Worked now, I think I added a glossary and the language consistency plugin did the rest.)

**Comment by duncte123** [comment]
No that is not an error and you are required to join our discord so we can stay in touch with you
