### ISSUE TITLE
Sort "Submissions Open" by deadline

### ISSUE THREAD

**Issue by Edenal** [esamarathon/oengusio#72]
### What is the feature?

![image](https://user-images.githubusercontent.com/19750421/119255476-576dee00-bbbc-11eb-8dda-5df8ed5c9cb5.png)
Submissions open are sorted by when the event is happening, rather than when the deadline for submissions are. 

This can be misleading when some marathons are planned 6 months in advance and some 6 days.

**Comment by duncte123** [comment]
Just checked the code, they are being sorted ascending by the start date of the marathon
