### ISSUE TITLE
"Submissions close a day ago"

### ISSUE THREAD

**Issue by Planks** [esamarathon/oengusio#91]
### Describe the bug

![image](https://user-images.githubusercontent.com/16325321/122011190-21d3b380-cdbc-11eb-92e5-bcc9e6583053.png)

### How to reproduce

Load the homepage

### Expected behavior

Event should appear in correct order

**Comment by duncte123** [comment]
Could be the scheduler dying or them opening it manually again

**Comment by BobChao87** [comment]
Issue has recurred with SEGABLAST 2021 - SGES (sgessega21)
