### ISSUE TITLE
Mass reject/accept button

### ISSUE THREAD

**Issue by EnglishBen** [esamarathon/oengusio#93]
### What is the feature?

It is incredibly tedious to manually reject a high number of submissions for a large-scale marathon such as ESA. For example we have 1000 runs submitted, we accept 100 of them and list 50 as backups. It is very tedious to manually reject the remaining 850 (especially because only one person can do this at a time.

### Describe the feature

A simple button/option that could do one of two things:

A - Automatically mark "To Do" runs as "Rejected", allowing us to filter the remainder with a single click.

B - Toggle all runs to rejected/accepted right away, so we can manually edit whichever needs the least busy-work.

**Comment by duncte123** [comment]
Doesn't option `A` happen automatically already?
