### ISSUE TITLE
Discord name in profile page is empty for certain users

### ISSUE THREAD

**Issue by Hoishin** [esamarathon/oengusio#94]
### Describe the bug

`discordName` field and Discord name in user profile page have been added at some point.

- if user connected oengus account with discord *after* that, discord name is shown in profile page and `discordName` field from API
- if user connected oengus account with discord *before* that, discord name is not shown in profile page and `discordName` is empty

### How to reproduce

1. https://oengus.io/user/profile/Hoishin doesn't show Discord name, even though Hoishin logs in with Discord
2. https://oengus.io/user/profile/pasta04 shows Discord name, they have re-connected with Discord today

### Expected behavior

In both cases it should show Discord name in profile

### Desktop (please complete the following information)

It's happening on API level.

- OS: doesn't matter
- Browser: doesn't matter
- Version: doesn't matter

**Comment by duncte123** [comment]
This is not a bug. 

As stated in the FAQ channel on discord users will simply have to re-sync their discord as this information was not stored previously (hence it being empty).

**Comment by Hoishin** [comment]
what would be the best way to get the list of discord user ID or display names for accepted runners?

**Comment by duncte123** [comment]
> what would be the best way to get the list of discord user ID or display names for accepted runners?

Ask them to re-sync because the discord ID is not exposed to the public. If you just want a list of all runners you can fetch the submissions and map it to the user objects for each submission
