### ISSUE TITLE
Rewrite backend in javalin

### ISSUE THREAD

**Issue by duncte123** [esamarathon/oengusio#98]
Spring is a nice backend system but it does not play nicely with our use case. We will be switching to [javalin 4](https://javalin.io/documentation) to give the backend a fresh start and also make sure the code will be maintained properly.

Before the backend will be rewritten there are a few things that need to be worked out as Javalin does not have a build-in replacement for these items.
The items that need research are:
- Request validation => https://javalin.io/documentation#validation
- Database migrations
- Database connectivity (preferably via models)
- Documentation => https://github.com/swagger-api/swagger-core
- Prometheus data

Missing items will be added to this list if needed

**Comment by tipsy** [comment]
I do love speedrunning (watching the TP run now), so I would definitely go for Javalin 😄
